name: Generate Snake

on:
  schedule: # Executa automaticamente uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ingridrayane1998
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
